# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-22 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20160522_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='state',
            field=models.CharField(choices=[('N', 'New'), ('A', 'A'), ('W', 'W'), ('L', 'L')], default='N', max_length=1),
        ),
    ]
